### ISSUE TITLE
Master Tracking Issue: #00000

### ISSUE THREAD

**Issue by leonkalema** [leonkalema/rimbo#1]
**Objective**
A user would love to drag and organise the to watch list. By ordering them in top priority of when they plan to watch that particular movie. So the next time they login they can basically have their to watch list in that order.  
A use can also set the dates and time they plan to watch that movie. 

Tech Spec
![image](https://user-images.githubusercontent.com/23662700/57191562-6034ee00-6f27-11e9-8514-a7e6856aa2c7.png)

TODOs:

- [ ] Drag movies by priority.
 

- [ ] Option to set time or ignore. 

- [ ] Set the time to watch on drag.

- [ ] If the set time is available alert user ( with time already set to another movie name) and prompt to change time. 

- [ ] If set time the move movie object in that order.

- [ ] Remind the user about the movie they are to watch two times, first 1 day before and then 6 hrs to the time. 

- [ ] Prompt user to login or register to keep current settings. 

- [ ] Unit Tests :) Always. 

**Notes**
For any design issues kindly reach the UX designer. But you are amazing and gonna do this great.
